spring:
  application:
    name: projeto-petshop-web
  datasource:
    url: jdbc:postgresql://localhost:5432/sistema_petshop
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true